# Generate code for mlir ir for db dialect from the dict AST generated by parser
from kero.engine import _keroEngine
from kero._engine._kero.dialects import func, db
import kero._engine._kero.ir as ir

from .parser import ScanOp, OutputOp
from ..arrow.type_resolve import DBTypes, Table, Column, PYARROW_TO_DB_TYPES

import typing as t


CACHE = {}


def make_dbtable_type(node: Table, context):
    if node.name in CACHE:
        return CACHE[node.name]

    if node.name != "output_t":
        for column in node.columns.values():
            column.dtype = PYARROW_TO_DB_TYPES[column.dtype]
    
    table_t = ir.Type.parse(repr(node), context)

    CACHE[node.name] = table_t
    return table_t


class IRGen:
    def __init__(self, query_name: str, operations):
        self.operations = operations
        self.context = ir.Context()
        self.loc = ir.Location.unknown(self.context)
        self.module = ir.Module.create(self.loc)
        self.func_name = query_name
        self.generator = None

        # register DB dialect + all others
        _keroEngine.register_dialect(self.context)

    def emit_ir(self):
        with self.context:
            with self.loc, ir.InsertionPoint(self.module.body):
                # create a function
                # the function should take the input of table
                table_t = make_dbtable_type(self.operations[0].input_table, self.context)
                result_t = make_dbtable_type(self.operations[-1].output_table, self.context)
                ftype = ir.FunctionType.get(inputs=[table_t], results=[result_t])

                func_op = func.FuncOp(self.func_name, ftype)
                entry_block = ir.Block.create_at_start(func_op.body, ftype.inputs)
                self.generator = AstToKeroConverter(self.context, self.loc, self.module, entry_block)

                out = entry_block.arguments[0]
                for operation in self.operations:
                    out = self.generator.resolve_node(operation, out)

                with ir.InsertionPoint(entry_block):
                    func.return_([out])


class AstToKeroConverter:
    def __init__(
            self, 
            context: ir.Context, 
            location: ir.Location, 
            module: ir.Module, 
            block: ir.Block,
    ):
        self.block = block
        self.context = context
        self.loc = location
        self.module = module
        self.op_map = self._node_to_op_map()
        self.type_map = self._node_to_type_map()

    def resolve_node(self, node, inputs):
        """
        Identifies the node and calls appropriate function to generate 
        operation
        """
        with self.loc , ir.InsertionPoint(self.block):
            op = self.op_map[type(node)](node, inputs)
            return op

    def type_conversion(self, node):
        """Convert DB AST types to DB Dialect types"""
        with self.loc, ir.InsertionPoint(self.block):
            db_type = self.type_map[type(node)](node, self.context)

    def _make_scan_op(self, node: ScanOp, inputs):
        with self.loc, ir.InsertionPoint(self.block):
            table_t =  make_dbtable_type(node.input_table, self.context)
            scan_op = db.scan(output=table_t, table=inputs)
            return scan_op

    def _make_output_op(self, node: OutputOp, inputs):
        with self.loc, ir.InsertionPoint(self.block):
            table_t = make_dbtable_type(node.output_table, self.context)
            output_op = db.output(output=table_t, table=inputs, select=node.attribute["select"])
            return output_op

    def _node_to_type_map(self):
        map = {
            Table: make_dbtable_type
        }
        return map

    def _node_to_op_map(self):
        map = {
            ScanOp: self._make_scan_op,
            OutputOp: self._make_output_op
        }

        return map
